version: '3.8'

services:
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env
    ports:
      - '3308:3306'
    volumes:
      - shop:/var/lib/mysql

  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./env/backend.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql

volumes:
  shop: