version: '3.8'

services:
  mysql:
    platform: linux/amd64
    image: 'mysql:5.7'
    env_file:
      - ./.env
    ports:
      - '3308:3306'

  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
